### ISSUE TITLE
Do not disturb feature won't work correctly

### ISSUE THREAD

**Issue by Alkesst** [Alkesst/pytelbot#7]
Attribute do_not_disturb is useless until you use /molestar or /Molestar in chats. 

- What to do:
     - Fill the dictionary with data from the database, that way avoids raising exceptions `KeyError`

**Comment by melchor629** [comment]
```telegram.ext.dispatcher - 2018-07-24 14:14:14,429 - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/messagehandler.py", line 169, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/app/pytel_bot/bot_actions.py", line 326, in botijo_react
    if not BotActions.do_not_disturb[chat_id]:
KeyError: -1001104881568```

Maybe using `BotActions.do_not_disturb.get(chat_id, False)` is better.
